autodocs:
  port: 8083

gitlab:
  url: https://gitlab.example.com
  token: jhgUIJHG239kjhfd89723hoishfsegsd

repos:
  - name: Cyrill/autodocs-ci-test
    extract_to: /var/www/docs/autodocs-ci-test
    stages:
      - docs
